### ISSUE TITLE
Buildings

### ISSUE THREAD

**Issue by qweytr** [PhelanBavaria/ancienttimeline#47]
I have now finished adding buildings to ET and I could soon start working on the buildings for AT. Before I can start adding new buildings, we must establish what exact buildings there are going to be. Here's a basic template:

Trade buildings (4-5):
- Meeting Place
- Marketplace
- Trading Post
- Grand Market

Production buildings (4-5):
- Granary
- Storehouse
- Forge
- Workshop

Tax buildings (2-4):
- Tax Collector
- Coin Mint

Unrest buildings (2-3):
- Town Watch
- Guardhouse

Manpower buildings (2-3):
- Barracks
- Armory

Land forcelimit buildings (2-3):
- Training Fields
- Military Academy

Ship construction buildings (2-3):
- Shipyard
- Grand Shipyard

Naval forcelimit buildings (2-3):
- Dock
- Naval Base

Religion buildings (2-4):
- Monument
- Temple

Transportation (2-3):
- Dirt Road
- Paved Road

Forts (4):
- Walls
- Hill Fort
- Fortress
- Stronghold

Manufactories (5):
- Wharf (naval supplies, fish, tropical wood, salt)
- Weaponsmith (copper, iron)
- Weaver (wool, cloth, silk, dyes)
- Farmhouse (coffee, cotton, sugar, tobacco, cocoa, grain, tea, wine, spices)
- Trade Center (ivory, chinaware, slaves, fur)

Let me know if you can think of good names for the buildings marked with a question mark. You can also suggest new buildings categories.

**Comment by PhelanBavaria** [comment]
Some ideas would be:
- Coin Mint
- Street
- Training Grounds
- Town Watch
- Quarry

**Comment by qweytr** [comment]
I have edited Coin Mint and Town Watch into the first post, but I don't know what category to put the others in.

**Comment by Firesoul7** [comment]
I suggest that Marketplace could perhaps be moved to the first trade slot, and Bazaar installed as the second trade slot. In essence a Marketplace would be somewhere where people come from time to time to trade, whereas a Bazaar is permanent, goods are traded there all the time. As for tax building slot one, perhaps a Tax-collector building, which would basically be an office where the local tax collector stays in order to collect from the local people. The second Manpower slot could be Stables. Stables required more space than Barracks, so what tended to happen was that small towns would just have Barracks, but as their military infrastructure expanded they were also able to accommodate cavalry, and would train both. Ramesses II in particular was famous for his great stables, training both infantry and chariots. (Of course, it wouldn't be possible to limit them in this way ingame, and Stables would just give a boost to manpower, rather than unlocking cavalry or something like that). I think Quarry would probably be a Production building.

**Comment by qweytr** [comment]
Bazaar would be a bit too specific in my opinion. It doesn't really fit anything outside Middle East. Stables sounds strange as an upgrade from barracks, as the two are fundamentally different buildings. I could perhaps be added in its own category.

**Comment by Firesoul7** [comment]
I don't know of any stables in the ancient world that was only a stables.
All ancient military stables I know of were responsible for both infantry
and cavalry. Bazaar isn't all that specific, it's the term used.
en.wikipedia.org/wiki/Edward-Dodwell#/media/File:Bazar_of_Athens.jpg

**Comment by Firesoul7** [comment]
en.wikipedia.org/wiki/Bazaar look at the definition. Just because a word
originated in the Middle East does not make it invalid outside the Middle
East.

**Comment by qweytr** [comment]
We can use stables as an upgrade to barracks if we can't come up with anything better. That bazaar was when the Ottomans ruled Greece. It was an Ottoman bazaar, not a Greek one. Ideally we would have culturally named buildings like Bazaar for Persians and Agora for Greeks, but that's not possible. Essentially both terms are equivalent to marketplace.

**Comment by Firesoul7** [comment]
Then perhaps for slot one we could have something like a Meeting Place, as they had in Mongolia. People would gather from all the villages once per year to trade, share stories, etc, but such places were abandoned at all other times. Such sites were commonplace throughout the ancient world, and
further the main way of doing things. It's possible that this was the purpose of Stonehenge and the like.

**Comment by qweytr** [comment]
I have now updated the list with more building names. The maximum number of buildings is 45. The list currently has 33, so there's room to add a few more and any suggestions are still welcome.

**Comment by Firesoul7** [comment]
I can't think of any. I would consider this issue closed. It can be reopened again later as a non-Release 1.0.0 issue perhaps. Of course, we should wait until the others have weighed in.

**Comment by qweytr** [comment]
I'll close this once the buildings have been implemented.

**Comment by qweytr** [comment]
Buildings are done.
